# Generated by Django 5.0.1 on 2024-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user_task_task_create_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_create_by',
        ),
        migrations.AddField(
            model_name='task',
            name='task_create_by',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.type'),
        ),
    ]
