# Generated by Django 5.0.1 on 2024-01-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_type_remove_task_task_create_by_task_task_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type_name',
            field=models.ManyToManyField(blank=True, to='tasks.type'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_create_by',
        ),
        migrations.AddField(
            model_name='task',
            name='task_create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.user'),
        ),
    ]
